### ISSUE TITLE
The version of mujoco and dm_control

### ISSUE THREAD

**Issue by nigelyaoj** [Pavan-Samtani/soccer-spinningup#1]
Great work! However, could you specify the version of the mujoco and dm_control you run your code on? I am trying to train the dataset but find the ball-goal distances calculated from the observations of two teammates are different. Thank you.

**Comment by Pavan-Samtani** [comment]
The version of Mujoco used in this project is 2.0.

The specific SHA of dm_control is d1fe1d14fb229d3ad784e40d8c54491d30e1f08a, which you can install with the command:
`pip install git+https://github.com/deepmind/dm_control.git@d1fe1d14fb229d3ad784e40d8c54491d30e1f08a`

How are you comparing the ball-goal distances between both teammates? 
If you have instantiated a 2v2 task, then the ball-opponent goal distance should be the 13th (index 12) component of every observation vector, which should be the same between players 1 and 2 (indexes 0 and 1), and between players 3 and 4 (indexes 2 and 3).

**Comment by nigelyaoj** [comment]
Thanks for your response. It's helpful to me. I may check my code first.
